export const translations = {
  en: {
    // Nav
    dashboard: "Dashboard",
    tournaments: "Tournaments",
    leagues: "Leagues",
    players: "Players",
    users: "Users",
    myDashboard: "My Dashboard",
    signOut: "Sign out",

    // Auth
    signIn: "Sign In",
    register: "Register",
    login: "Login",
    createAccount: "Create Account",
    email: "Email",
    password: "Password",
    displayName: "Display name",
    authFailed: "Authentication failed.",
    viewPublic: "View public tournaments →",

    // Landing
    tournamentManager: "Tournament Manager",
    adminAccess: "Admin & Staff access",
    liveResults: "Live results",
    watch: "WATCH",

    // Dashboard
    welcomeBack: "Welcome back,",
    totalTournaments: "Total Tournaments",
    active: "Active",
    finished: "Finished",
    recentTournaments: "Recent Tournaments",
    viewAll: "View all →",
    noTournaments: "No tournaments yet",
    createFirst: "Create first tournament",

    // Tournaments page
    createTournament: "Create tournament",
    tournamentName: "Tournament name...",
    maxPlayers: "Max players",
    creating: "Creating...",
    noTournamentsFound: "No tournaments found",
    manage: "Manage",
    all: "All",

    // Tournament detail
    openRegistration: "Open Registration",
    startGroupStage: "Start Group Stage",
    startKnockout: "Start Knockout",
    finishTournament: "Finish Tournament",
    processing: "Processing...",
    overview: "Overview",
    groups: "Groups",
    matches: "Matches",
    standings: "Standings",
    bracket: "Bracket",
    qualifiers: "Qualifiers",
    tbd: "TBD",
    noGroupsYet: "No groups yet",
    groupsAutoGenerated: "Groups are generated automatically when you start the Group Stage",
    noMatchesYet: "No matches yet",
    globalRanking: "Global Ranking",
    howManyQualify: "How many qualify for Knockout?",
    playersInStandings: "players in standings",
    setQualifiersMin: "Set how many players qualify for Knockout (minimum 2).",
    auto: "AUTO",

    // Players panel in tournament
    addPlayers: "Add players to tournament",
    searchPlayer: "Search player...",
    noPlayersAvailable: "No players available",
    enroll: "Enroll",
    request: "Request",
    pendingApproval: "Pending approval",
    approve: "Approve",
    reject: "Reject",

    // Players page
    bladers: "bladers registered",
    addPlayer: "Add player",
    editing: "Editing",
    playerName: "Player name...",
    save: "Save",
    add: "Add",
    cancel: "Cancel",
    noPlayersYet: "No players yet",
    edit: "Edit",
    remove: "Remove",

    // Match card
    live: "LIVE",
    wins: "Wins",
    deleteMatch: "Delete match",

    // Standings
    w: "W",
    l: "L",
    pf: "PF",
    pa: "PA",
    diff: "+/-",
    played: "P",

    // Status badges
    DRAFT: "Draft",
    REGISTRATION: "Registration",
    GROUP_STAGE: "Group Stage",
    KNOCKOUT: "Knockout",
    FINISHED: "Finished",

    // Roles
    admin: "Admin",
    staff: "Staff",
    player: "Player",

    // Player portal
    availableTournaments: "Available Tournaments",
    myEnrollments: "My Enrollments",
    enrollMe: "Enroll",
    requestEnroll: "Request Enrollment",
    alreadyEnrolled: "Enrolled ✓",
    pendingEnrollment: "Pending approval",
    noOpenTournaments: "No open tournaments right now",
    myStatus: "My status",
    notLinked: "Player profile not found. Contact an admin.",
    view: "View",

    // Leagues
    createLeague: "Create league",
    leagueName: "League name...",
    leagueDescription: "Description (optional)",
    noLeagues: "No leagues yet",
    leagueStandings: "League Standings",
    leagueEvents: "Rounds",
    noLeagueEvents: "No rounds assigned to this league yet",
    noFinishedEvents: "No finished rounds yet — standings will appear once rounds complete",
    pointsScale: "Points scale",
    points: "Points",
    eventsPlayed: "Events",
    typeTournament: "Tournament",
    typeLeagueEvent: "League Round",
    selectLeague: "League",
    selectLeaguePlaceholder: "Select a league...",
    judge: "Judge",
    noJudge: "No judge",
    removeJudge: "Remove judge",
    judgeCannotBePlayer: "This person is a player in this group and cannot be its judge.",
    myLeagues: "My Leagues",
    notInAnyLeague: "You are not enrolled in any league yet",
    podiums: "Podiums",
    rounds: "Rounds",

    // Misc
    tournamentNotFound: "Tournament not found.",
    deleteConfirm: "Delete this tournament and all its data?",
    back: "← Tournaments",
    inProgress: "In Progress",
    finishedTournaments: "Finished",
    noTournamentsInProgress: "No active tournaments",
  },
  es: {
    // Nav
    dashboard: "Panel",
    tournaments: "Torneos",
    leagues: "Ligas",
    players: "Jugadores",
    users: "Usuarios",
    myDashboard: "Mi Panel",
    signOut: "Cerrar sesión",

    // Auth
    signIn: "Iniciar sesión",
    register: "Registrarse",
    login: "Entrar",
    createAccount: "Crear cuenta",
    email: "Correo electrónico",
    password: "Contraseña",
    displayName: "Nombre de usuario",
    authFailed: "Error de autenticación.",
    viewPublic: "Ver torneos públicos →",

    // Landing
    tournamentManager: "Gestor de Torneos",
    adminAccess: "Acceso Admin y Staff",
    liveResults: "Resultados en vivo",
    watch: "VER",

    // Dashboard
    welcomeBack: "Bienvenido,",
    totalTournaments: "Total Torneos",
    active: "Activos",
    finished: "Finalizados",
    recentTournaments: "Torneos Recientes",
    viewAll: "Ver todos →",
    noTournaments: "Sin torneos aún",
    createFirst: "Crear primer torneo",

    // Tournaments page
    createTournament: "Crear torneo",
    tournamentName: "Nombre del torneo...",
    maxPlayers: "Máx. jugadores",
    creating: "Creando...",
    noTournamentsFound: "No se encontraron torneos",
    manage: "Gestionar",
    all: "Todos",

    // Tournament detail
    openRegistration: "Abrir Registro",
    startGroupStage: "Iniciar Fase de Grupos",
    startKnockout: "Iniciar Eliminación",
    finishTournament: "Finalizar Torneo",
    processing: "Procesando...",
    overview: "Resumen",
    groups: "Grupos",
    matches: "Partidas",
    standings: "Clasificación",
    bracket: "Bracket",
    qualifiers: "Clasificados",
    tbd: "Por definir",
    noGroupsYet: "Sin grupos aún",
    groupsAutoGenerated: "Los grupos se generan automáticamente al iniciar la Fase de Grupos",
    noMatchesYet: "Sin partidas aún",
    globalRanking: "Clasificación Global",
    howManyQualify: "¿Cuántos clasifican al Knockout?",
    playersInStandings: "jugadores en clasificación",
    setQualifiersMin: "Define cuántos jugadores clasifican al Knockout (mínimo 2).",
    auto: "AUTO",

    // Players panel in tournament
    addPlayers: "Añadir jugadores al torneo",
    searchPlayer: "Buscar jugador...",
    noPlayersAvailable: "No hay jugadores disponibles",
    enroll: "Inscribir",
    request: "Solicitar",
    pendingApproval: "Pendiente de aprobación",
    approve: "Aprobar",
    reject: "Rechazar",

    // Players page
    bladers: "bladers registrados",
    addPlayer: "Añadir jugador",
    editing: "Editando",
    playerName: "Nombre del jugador...",
    save: "Guardar",
    add: "Añadir",
    cancel: "Cancelar",
    noPlayersYet: "Sin jugadores aún",
    edit: "Editar",
    remove: "Eliminar",

    // Match card
    live: "EN VIVO",
    wins: "Victorias",
    deleteMatch: "Eliminar partida",

    // Standings
    w: "V",
    l: "D",
    pf: "PF",
    pa: "PC",
    diff: "+/-",
    played: "J",

    // Status badges
    DRAFT: "Borrador",
    REGISTRATION: "Registro",
    GROUP_STAGE: "Fase Grupos",
    KNOCKOUT: "Eliminación",
    FINISHED: "Finalizado",

    // Roles
    admin: "Admin",
    staff: "Staff",
    player: "Jugador",

    // Player portal
    availableTournaments: "Torneos Disponibles",
    myEnrollments: "Mis Inscripciones",
    enrollMe: "Inscribirme",
    requestEnroll: "Solicitar inscripción",
    alreadyEnrolled: "Inscrito ✓",
    pendingEnrollment: "Pendiente de aprobación",
    noOpenTournaments: "No hay torneos abiertos en este momento",
    myStatus: "Mi estado",
    notLinked: "Perfil de jugador no encontrado. Contacta a un admin.",
    view: "Ver",

    // Leagues
    createLeague: "Crear liga",
    leagueName: "Nombre de la liga...",
    leagueDescription: "Descripción (opcional)",
    noLeagues: "Sin ligas aún",
    leagueStandings: "Tabla de la Liga",
    leagueEvents: "Jornadas",
    noLeagueEvents: "No hay jornadas asignadas a esta liga aún",
    noFinishedEvents: "Sin jornadas finalizadas aún — la tabla aparecerá cuando terminen las jornadas",
    pointsScale: "Escala de puntos",
    points: "Puntos",
    eventsPlayed: "Eventos",
    typeTournament: "Torneo",
    typeLeagueEvent: "Jornada",
    selectLeague: "Liga",
    selectLeaguePlaceholder: "Selecciona una liga...",
    judge: "Juez",
    noJudge: "Sin juez",
    removeJudge: "Quitar juez",
    judgeCannotBePlayer: "Esta persona es jugador en este grupo y no puede ser su juez.",
    myLeagues: "Mis Ligas",
    notInAnyLeague: "Aún no estás inscrito en ninguna liga",
    podiums: "Podios",
    rounds: "Jornadas",

    // Misc
    tournamentNotFound: "Torneo no encontrado.",
    deleteConfirm: "¿Eliminar este torneo y todos sus datos?",
    back: "← Torneos",
    inProgress: "En Curso",
    finishedTournaments: "Finalizados",
    noTournamentsInProgress: "No hay torneos activos",
  },
} as const;

export type Lang = keyof typeof translations;
export type TranslationKey = keyof typeof translations.en;
